# Needed by https://github.com/conda-forge/rocr-runtime-feedstock/blob/4710de93b8c0be9c0dd95c57018decfbd5ccd91f/recipe/conda_build_config.yaml#L1
c_stdlib_version:   # [linux]
  - "2.28"          # [linux]
