{% set name = "rocminfo" %}
{% set version = "7.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/rocm-systems/releases/download/rocm-{{ version }}/rocminfo.tar.gz
  sha256: 6f3235bea6b8e92460de66a7f40366d17e20ae36693324eccd3eb3fa4e75cc98

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - numactl
    - rocm-core {{ version }}
    - rocr-runtime {{ version }}
  run:
    - rocr-runtime {{ version }}
    - libnuma

test:
  commands:
    # Can't run this command without an AMD GPU
    - test -f $PREFIX/bin/rocminfo
    - test -f $PREFIX/bin/rocm_agent_enumerator
    - msg=$($PREFIX/bin/rocminfo 2>&1; test $? -eq 1) && test "$msg" = "$(echo -e '\033[31mROCk module is NOT loaded, possibly no GPU devices\033[0m')"   # [CI]

about:
  home: https://github.com/ROCm/rocminfo
  license: NCSA
  license_family: MIT
  license_file: License.txt
  summary: 'ROCm Application for Reporting System Info'

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
    - conda-forge/rocm-core
 
